platform:ios,'8.0'
target 'JianGuo’ do
pod ‘AFNetworking‘, ‘~> 3.0’
pod ‘MJRefresh’, ‘~> 3.1.9’
pod ‘MJExtension’, ‘~> 3.0.10’
pod ‘SDWebImage’, ‘~> 3.8.0’
pod ‘Masonry’, ‘~> 1.0.1’
pod ‘SDCycleScrollView’, ‘~> 1.61’
pod 'SVProgressHUD'
pod 'WZLBadge', ‘~> 1.2.4’
pod 'UITableView+FDTemplateLayoutCell', ‘~> 1.5.beta’
pod 'FMDB', ‘~> 2.6.2’

pod 'IQKeyboardManager'
pod 'MLLabel' , '~> 1.9.2'
pod 'pop', '~> 1.0.9'
#pod 'YYKit'

pod 'FDStackView' , '~> 1.0'
pod 'DACircularProgress' , '~> 2.3.1'
#pod 'ChatKit' , '~> 0.4.2'

pod 'AVOSCloud', ‘~> 3.3.5’
pod 'AVOSCloudIM', ‘~> 3.3.5’

#pod 'AMapSearch' #搜索服务SDK
#pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤用)
#pod 'AMapLocation’
pod 'BeeCloud', '~> 3.6.1' #包含支付宝微信银联三个渠道
end